// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfkfsfixcpkswsokrpti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJma2ZzZml4Y3Brc3dzb2tycHRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNjExMTcsImV4cCI6MjA1NDkzNzExN30.51hXixEjYb37s7D90Z-58bDk3GCtCloU4m8gZhqeqHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);